"""Seed prototype prompts for training classifiers.

Contains:
- SIMPLE_PROTOTYPES / COMPLEX_PROTOTYPES: binary complexity classifier
- INTENT_PROTOTYPES: multi-category intent classifier (8 categories)
"""

SIMPLE_PROTOTYPES = [
    "What is the capital of France?",
    "Who wrote Romeo and Juliet?",
    "What year did World War II end?",
    "How many continents are there?",
    "What is the chemical symbol for gold?",
    "What language do they speak in Brazil?",
    "Who painted the Mona Lisa?",
    "What is the largest planet in our solar system?",
    "What is the speed of light?",
    "How many sides does a hexagon have?",
    "What is 25 times 4?",
    "Calculate 150 divided by 3",
    "What is 17 plus 38?",
    "What is 10% of 250?",
    "Convert 5 kilometers to miles",
    "Define photosynthesis",
    "What does GDP stand for?",
    "What is an algorithm?",
    "Define the word 'serendipity'",
    "What is a metaphor?",
    "How do you say hello in Japanese?",
    "Translate 'thank you' to Spanish",
    "What is 'goodbye' in French?",
    "Is Python a compiled language?",
    "Does the Earth revolve around the Sun?",
    "Is 7 a prime number?",
    "Can penguins fly?",
    "Is HTML a programming language?",
    "Convert this text to uppercase: hello world",
    "List the days of the week",
    "Sort these numbers: 5, 2, 8, 1, 9",
    "What is today's date?",
    "Reverse the string 'hello'",
    "Hello, how are you?",
    "Good morning!",
    "Tell me a joke",
    "What's your name?",
    "What is the boiling point of water?",
    "What timezone is New York in?",
    "What is the population of Tokyo?",
    "How tall is Mount Everest?",
    "What is the atomic number of carbon?",
    "Summarize this in one sentence",
    "Give me a synonym for 'happy'",
    "What is the opposite of 'cold'?",
    "Name three primary colors",
    "What comes after Tuesday?",
    "Read the file config.yaml",
    "Show me the contents of README.md",
    "What's in the .env file?",
    "List all files in the src directory",
    "Find all Python files in this project",
    "Run npm install",
    "Check the git status",
    "What branch am I on?",
    "Show me the last 5 git commits",
    "Run the tests",
    "Search for the latest version of React",
    "What is the current price of Bitcoin?",
    "Look up the npm package express",
    "Fetch the docs for FastAPI Query parameters",
    "What does this function do?",
    "What's the syntax for a Python list comprehension?",
    "How do I create a new branch in git?",
    "What port is the server running on?",
    "Show me the imports in main.py",
    "Change the port from 3000 to 8080",
    "Add a newline at the end of this file",
    "Rename the variable x to count",
    "Fix this typo: 'recieve' should be 'receive'",
    "Remove the unused import on line 3",
    "What version of Node is installed?",
    "How much disk space is available?",
    "Is the database running?",
    "What's my IP address?",
    "Show the environment variables",
]

COMPLEX_PROTOTYPES = [
    "Design a microservices architecture for a real-time multiplayer game with matchmaking, leaderboards, and anti-cheat systems",
    "Architect a distributed event-sourcing system for a financial trading platform that handles millions of transactions per second",
    "Design a scalable notification system that supports push, email, SMS, and in-app channels with user preferences and rate limiting",
    "Create a system design for a URL shortener that handles 100 million daily requests with analytics",
    "Explain the trade-offs between consistency and availability in distributed systems, using real-world examples from companies like Netflix and Amazon",
    "Compare and contrast the CAP theorem implications for SQL vs NoSQL databases in a microservices context, then recommend an approach for an e-commerce platform",
    "Analyze the economic impacts of remote work adoption on urban real estate markets, transportation infrastructure, and local businesses",
    "Walk me through the reasoning behind choosing between a monolithic and microservices architecture for a startup's MVP",
    "Implement a thread-safe LRU cache in Python with TTL support, size limits, and cache statistics tracking",
    "Write a complete REST API with authentication, rate limiting, pagination, and comprehensive error handling using FastAPI",
    "Build a React component library with a design system that includes theming, accessibility, responsive design, and documentation",
    "Implement a B-tree data structure with insert, delete, search, and range query operations, including rebalancing",
    "Create a Python decorator that implements retry logic with exponential backoff, jitter, circuit breaking, and logging",
    "Debug this memory leak in a Node.js application that occurs during WebSocket connections under high concurrency, and explain the GC implications",
    "Optimize this SQL query that takes 30 seconds on a table with 50 million rows, considering indexing strategies, query plan analysis, and partitioning",
    "Profile and optimize a Python data pipeline that processes 10GB CSV files, currently taking 4 hours to complete",
    "Compare the latest transformer architectures (GPT-4, Claude, Gemini, Llama) in terms of training methodology, context handling, and real-world performance benchmarks",
    "Synthesize the current research on quantum error correction and explain the implications for practical quantum computing timelines",
    "Analyze the trade-offs between different consensus algorithms (Paxos, Raft, PBFT) for blockchain applications",
    "Write a short story exploring the ethical implications of AI consciousness, incorporating themes from both Eastern and Western philosophy",
    "Create a detailed fictional world with its own political system, economy, religion, and history spanning 1000 years",
    "Write a technical blog post explaining category theory concepts using cooking metaphors, targeted at software engineers",
    "Prove that the halting problem is undecidable using a diagonalization argument, and explain the practical implications for software verification",
    "Derive the backpropagation algorithm from first principles and explain how automatic differentiation relates to it",
    "Prove the correctness of Dijkstra's algorithm and analyze its time complexity under different priority queue implementations",
    "Design a database schema for a social media platform, then write migration scripts, explain indexing strategy, outline the caching layer, and describe the data archival process",
    "Create a complete CI/CD pipeline configuration including build, test, security scanning, staging deployment, canary releases, and rollback procedures",
    "Build a comprehensive monitoring and alerting system covering application metrics, infrastructure health, business KPIs, and incident response automation",
    "Perform a security audit of this authentication flow, identifying potential vulnerabilities including OWASP Top 10 risks, and recommend mitigations with code examples",
    "Design a zero-trust security architecture for a multi-cloud environment with on-premises legacy systems",
    "Analyze the security implications of implementing OAuth 2.0 with PKCE for a mobile application, including threat modeling",
    "Develop a technical migration strategy to move a monolithic PHP application to a cloud-native architecture, including timeline, risk assessment, and team structure",
    "Create a comprehensive data strategy for a healthcare company transitioning to AI-driven diagnostics, addressing privacy, compliance, and technical infrastructure",
    "Design a disaster recovery plan for a financial services company with RPO of 15 minutes and RTO of 1 hour across multiple regions",
    "Analyze the performance characteristics of different garbage collection algorithms and recommend the optimal GC configuration for a latency-sensitive trading system",
    "Compare container orchestration approaches (Kubernetes, Nomad, ECS) for a company running 500 microservices across three cloud providers",
    "Evaluate the trade-offs of different state management solutions in a large-scale React application with offline-first requirements",
    "Refactor this 2000-line God class into a proper domain-driven design with bounded contexts, aggregates, and event handlers",
    "Review this distributed transaction implementation for correctness, identify race conditions, and propose a saga pattern alternative",
    "Analyze this machine learning pipeline for data leakage, feature engineering issues, and suggest improvements to the model evaluation strategy",
    "Explain how principles from control theory apply to designing auto-scaling systems, with specific implementation recommendations",
    "Connect concepts from game theory to microservices communication patterns and explain how to prevent cascade failures",
    "Apply information theory concepts to optimize data compression in a real-time video streaming architecture",
    "Diagnose why this Kubernetes cluster experiences intermittent pod evictions during peak traffic, analyzing resource limits, node pressure, and scheduler behavior",
    "Investigate a race condition in this concurrent Go program that only manifests under specific timing conditions with high CPU load",
    "Troubleshoot why this distributed cache shows inconsistent reads after network partitions despite using quorum-based replication",
    "Refactor the authentication system from JWT to session-based auth, updating all middleware, routes, and tests across the codebase",
    "Migrate this Express.js app to use TypeScript, converting all files, adding type definitions, and updating the build pipeline",
    "Split this monolithic app.py into a proper package structure with separate modules for routes, models, services, and utils",
    "The deploy is failing in CI — check the GitHub Actions logs, find the error, trace it back to the source file, and fix it",
    "Users are reporting 500 errors on the /api/checkout endpoint — check the logs, reproduce the issue, identify the root cause, and implement a fix",
    "The app is consuming 4GB of memory in production — profile the application, identify the memory leak, and fix it",
    "Read the existing database schema, then implement a new feature for user notifications with migrations, models, API endpoints, and WebSocket support",
    "Look at how authentication works in this codebase, then add OAuth2 login with Google and GitHub providers, including callback handlers and token refresh",
    "Analyze the current test suite, identify gaps in coverage, and write integration tests for all untested API endpoints",
    "Set up a complete development environment: clone the repo, install dependencies, configure the database, run migrations, seed test data, and verify everything works",
    "Create a new microservice that integrates with the existing API gateway — scaffold the project, implement the service, add Docker config, update the gateway routes, and write deployment manifests",
    "Audit all dependencies for security vulnerabilities, update the vulnerable ones, verify no breaking changes, and update the lockfile",
    "Analyze the current database query patterns, identify the N+1 queries, and refactor the ORM layer to use eager loading with proper join strategies",
    "Review the error handling across the entire API, standardize the error response format, add proper error codes, and implement a global exception handler",
    "Evaluate whether we should migrate from REST to GraphQL for this project, analyze the current endpoints, and create a migration plan with schema design",
    "Scrape the documentation site, extract all API endpoints and their parameters, generate TypeScript types, and create an API client library",
    "Monitor this web application for performance regressions — set up Lighthouse CI, configure budgets, and create alerts for Core Web Vitals degradation",
]


# ---------------------------------------------------------------------------
# Intent prototypes — ~20 examples per category for centroid generation
# ---------------------------------------------------------------------------

INTENT_PROTOTYPES = {
    "code_generation": [
        "Write a Python function to validate email addresses using regex",
        "Create a REST API endpoint for user registration with FastAPI",
        "Implement a binary search tree in TypeScript",
        "Build a React component for a sortable data table",
        "Write a Rust function that parses CSV files into structs",
        "Create a Python class for managing a connection pool",
        "Implement a WebSocket server in Node.js for real-time chat",
        "Write a Go function that implements rate limiting with token bucket",
        "Build a CLI tool in Python using Click for database migrations",
        "Create a middleware for Express.js that handles JWT authentication",
        "Write a Python script to process and transform JSON data files",
        "Implement a caching decorator with TTL support in Python",
        "Build a file upload handler with progress tracking in Flask",
        "Write a SQL migration to add user roles and permissions tables",
        "Create a GraphQL resolver for paginated query results",
        "Implement a retry mechanism with exponential backoff in JavaScript",
        "Write a Python generator for streaming large file processing",
        "Build a custom hook in React for managing form state and validation",
        "Create a Docker Compose configuration for a multi-service app",
        "Write unit tests for the user authentication module",
    ],
    "code_review": [
        "Review this pull request for potential issues and suggest improvements",
        "Check this function for edge cases and error handling gaps",
        "Review the API endpoint implementation for security best practices",
        "Analyze this code for potential memory leaks and resource management",
        "Review the database query for N+1 problems and optimization opportunities",
        "Check this React component for accessibility issues and performance",
        "Review the error handling strategy in this service layer",
        "Analyze this concurrent code for race conditions and thread safety",
        "Review the test suite for coverage gaps and testing best practices",
        "Check this authentication flow for security vulnerabilities",
        "Review the input validation logic for completeness and edge cases",
        "Analyze this API design for RESTful best practices and consistency",
        "Review the logging implementation for appropriate levels and information",
        "Check this configuration management for security and best practices",
        "Review the dependency injection setup for potential circular dependencies",
        "Analyze this ORM model for proper field types and constraints",
        "Review the caching strategy for cache invalidation correctness",
        "Check this middleware chain for proper ordering and error propagation",
        "Review the database transaction handling for atomicity guarantees",
        "Analyze this state management approach for potential issues",
    ],
    "architecture": [
        "Design a microservices architecture for an e-commerce platform",
        "Architect a real-time data pipeline for processing IoT sensor data",
        "Design the system architecture for a video streaming platform",
        "Plan the database schema and data model for a social media app",
        "Architect a multi-tenant SaaS platform with isolated data stores",
        "Design an event-driven architecture for order processing workflows",
        "Plan the infrastructure for a globally distributed application",
        "Design a caching architecture for a high-traffic content platform",
        "Architect a CI/CD pipeline for microservices with canary deployments",
        "Design a message queue system for handling async job processing",
        "Plan the migration strategy from monolith to microservices",
        "Design a scalable search infrastructure using Elasticsearch",
        "Architect a serverless backend for a mobile application",
        "Design the data replication strategy for multi-region deployment",
        "Plan a service mesh architecture for inter-service communication",
        "Design an API gateway with rate limiting and authentication",
        "Architect a real-time notification system with multiple channels",
        "Design a disaster recovery plan with RPO and RTO requirements",
        "Plan the technology stack for a new greenfield project",
        "Design a zero-trust network architecture for cloud infrastructure",
    ],
    "debugging": [
        "The API returns 500 errors intermittently under load — find the root cause",
        "Debug why this async function sometimes hangs and never resolves",
        "Find the memory leak causing the Node.js process to crash after 24 hours",
        "Debug why database connections are being exhausted in production",
        "Investigate why this React component re-renders infinitely",
        "Find why the CI pipeline fails only on certain branches",
        "Debug the race condition in this concurrent data processing pipeline",
        "Investigate why WebSocket connections drop after 60 seconds",
        "Find the root cause of intermittent test failures in the test suite",
        "Debug why the Docker container exits with code 137 under high memory use",
        "Investigate why the API response time degrades over the course of a day",
        "Find the cause of data inconsistency between the cache and database",
        "Debug why this CORS configuration works locally but fails in production",
        "Investigate the segmentation fault that occurs when processing large files",
        "Find why the OAuth callback fails for certain identity providers",
        "Debug the deadlock occurring in the database transaction handling",
        "Investigate why background jobs are silently failing without logging",
        "Find the root cause of the SSL handshake timeout in the load balancer",
        "Debug why environment variables are not being loaded in the container",
        "Investigate why the pagination returns duplicate results on certain pages",
    ],
    "security_analysis": [
        "Perform a security audit of the authentication and authorization system",
        "Analyze the API for OWASP Top 10 vulnerabilities and recommend fixes",
        "Review the password hashing and storage implementation for weaknesses",
        "Assess the input validation and sanitization across all endpoints",
        "Audit the session management for token theft and replay vulnerabilities",
        "Analyze the file upload handling for path traversal and injection risks",
        "Review the CORS and CSP headers configuration for security gaps",
        "Assess the database access layer for SQL injection vulnerabilities",
        "Audit the third-party dependencies for known security vulnerabilities",
        "Analyze the encryption implementation for cryptographic weaknesses",
        "Review the API rate limiting for potential abuse vectors",
        "Assess the logging system for sensitive data exposure risks",
        "Audit the OAuth implementation for token leakage vulnerabilities",
        "Analyze the container security configuration and image scanning",
        "Review the secrets management for hardcoded credentials and leaks",
        "Assess the network security including TLS configuration and firewall rules",
        "Audit the role-based access control for privilege escalation risks",
        "Analyze the error handling for information disclosure vulnerabilities",
        "Review the deployment pipeline for supply chain security risks",
        "Assess the data backup and recovery process for security compliance",
    ],
    "documentation": [
        "Write API documentation for the user management endpoints",
        "Create a README for the project with setup instructions and examples",
        "Document the database schema with entity relationship descriptions",
        "Write a migration guide for upgrading from v2 to v3 of the API",
        "Create developer onboarding documentation for new team members",
        "Document the deployment process including rollback procedures",
        "Write technical specifications for the new payment processing feature",
        "Create API reference documentation with request/response examples",
        "Document the error codes and their meanings for the API",
        "Write architecture decision records for recent design choices",
        "Create a troubleshooting guide for common production issues",
        "Document the environment configuration and required variables",
        "Write a changelog entry summarizing the features in this release",
        "Create a runbook for the on-call team covering incident response",
        "Document the testing strategy and how to run different test suites",
        "Write user-facing documentation for the new dashboard features",
        "Create a data dictionary describing all database tables and fields",
        "Document the CI/CD pipeline stages and their purposes",
        "Write a security practices guide for contributing developers",
        "Create inline code documentation for the core routing module",
    ],
    "general_qa": [
        "Explain the differences between REST and GraphQL APIs",
        "What are the pros and cons of using TypeScript over JavaScript?",
        "How does garbage collection work in Python and Java?",
        "Explain the CAP theorem and its implications for distributed systems",
        "What is the difference between horizontal and vertical scaling?",
        "How do WebSockets differ from HTTP long polling and SSE?",
        "Explain microservices vs monolithic architecture trade-offs",
        "What are design patterns and when should I use the factory pattern?",
        "How does Docker containerization work at a high level?",
        "Explain the difference between SQL and NoSQL databases",
        "What is event-driven architecture and when should I use it?",
        "How do message queues like Kafka and RabbitMQ differ?",
        "Explain the difference between authentication and authorization",
        "What are the benefits of using infrastructure as code?",
        "How does load balancing work and what algorithms are common?",
        "Explain SOLID principles with practical examples",
        "What is the difference between optimistic and pessimistic locking?",
        "How does TLS/SSL encryption work in web applications?",
        "Explain the concept of eventual consistency in distributed databases",
        "What are the trade-offs between serverless and traditional hosting?",
    ],
    "simple_qa": [
        "What is the capital of France?",
        "How many bytes in a kilobyte?",
        "What does HTTP stand for?",
        "What is the default port for PostgreSQL?",
        "What language is Django written in?",
        "Is Python dynamically typed?",
        "What does API stand for?",
        "What is the latest version of Node.js?",
        "How do you create a virtual environment in Python?",
        "What is a 404 error?",
        "What command installs npm packages?",
        "What is the shortcut for undo in VS Code?",
        "What file extension do TypeScript files use?",
        "How do you check the Git branch you're on?",
        "What is localhost?",
        "What does JSON stand for?",
        "How do you start a Python HTTP server?",
        "What is the difference between == and === in JavaScript?",
        "What port does HTTP use by default?",
        "What command lists running Docker containers?",
    ],
}
